INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1101', 'Aceh Selatan', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1102', 'Aceh Tenggara', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1103', 'Aceh Timur', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1104', 'Aceh Tengah', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1105', 'Aceh Barat', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1106', 'Aceh Besar', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1107', 'Pidie', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1108', 'Aceh Utara', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1109', 'Simeulue', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1110', 'Aceh Singkil', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1111', 'Bireuen', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1112', 'Aceh Barat Daya', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1113', 'Gayo Lues', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1114', 'Aceh Jaya', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1115', 'Nagan Raya', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1116', 'Aceh Tamiang', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1117', 'Bener Meriah', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1118', 'Pidie Jaya', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1171', 'Kota Banda Aceh', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1172', 'Kota Sabang', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1173', 'Kota Lhokseumawe', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1174', 'Kota Langsa', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1175', 'Kota Subulussalam', '11');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1201', 'Tapanuli Tengah', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1202', 'Tapanuli Utara', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1203', 'Tapanuli Selatan', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1204', 'Nias', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1205', 'Langkat', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1206', 'Karo', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1207', 'Deli Serdang', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1208', 'Simalungun', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1209', 'Asahan', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1210', 'Labuhanbatu', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1211', 'Dairi', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1212', 'Toba', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1213', 'Mandailing Natal', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1214', 'Nias Selatan', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1215', 'Pakpak Bharat', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1216', 'Humbang Hasundutan', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1217', 'Samosir', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1218', 'Serdang Bedagai', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1219', 'Batu Bara', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1220', 'Padang Lawas Utara', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1221', 'Padang Lawas', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1222', 'Labuhanbatu Selatan', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1223', 'Labuhanbatu Utara', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1224', 'Nias Utara', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1225', 'Nias Barat', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1271', 'Kota Medan', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1272', 'Kota Pematangsiantar', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1273', 'Kota Sibolga', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1274', 'Kota Tanjung Balai', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1275', 'Kota Binjai', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1276', 'Kota Tebing Tinggi', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1277', 'Kota Padangsidimpuan', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1278', 'Kota Gunungsitoli', '12');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1301', 'Pesisir Selatan', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1302', 'Solok', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1303', 'Sijunjung', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1304', 'Tanah Datar', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1305', 'Padang Pariaman', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1306', 'Agam', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1307', 'Lima Puluh Kota', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1308', 'Pasaman', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1309', 'Kepulauan Mentawai', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1310', 'Dharmasraya', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1311', 'Solok Selatan', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1312', 'Pasaman Barat', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1371', 'Kota Padang', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1372', 'Kota Solok', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1373', 'Kota Sawahlunto', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1374', 'Kota Padang Panjang', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1375', 'Kota Bukittinggi', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1376', 'Kota Payakumbuh', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1377', 'Kota Pariaman', '13');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1401', 'Kampar', '14');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1402', 'Indragiri Hulu', '14');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1403', 'Bengkalis', '14');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1404', 'Indragiri Hilir', '14');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1405', 'Pelalawan', '14');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1406', 'Rokan Hulu', '14');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1407', 'Rokan Hilir', '14');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1408', 'Siak', '14');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1409', 'Kuantan Singingi', '14');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1410', 'Kepulauan Meranti', '14');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1471', 'Kota Pekanbaru', '14');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1472', 'Kota Dumai', '14');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1501', 'Kerinci', '15');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1502', 'Merangin', '15');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1503', 'Sarolangun', '15');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1504', 'Batanghari', '15');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1505', 'Muaro Jambi', '15');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1506', 'Tanjung Jabung Barat', '15');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1507', 'Tanjung Jabung Timur', '15');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1508', 'Bungo', '15');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1509', 'Tebo', '15');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1571', 'Kota Jambi', '15');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1572', 'Kota Sungai Penuh', '15');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1601', 'Ogan Komering Ulu', '16');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1602', 'Ogan Komering Ilir', '16');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1603', 'Muara Enim', '16');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1604', 'Lahat', '16');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1605', 'Musi Rawas', '16');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1606', 'Musi Banyuasin', '16');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1607', 'Banyuasin', '16');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1608', 'Ogan Komering Ulu Timur', '16');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1609', 'Ogan Komering Ulu Selatan', '16');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1610', 'Ogan Ilir', '16');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1611', 'Empat Lawang', '16');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1612', 'Penukal Abab Lematang Ilir', '16');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1613', 'Musi Rawas Utara', '16');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1671', 'Kota Palembang', '16');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1672', 'Kota Pagar Alam', '16');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1673', 'Kota Lubuk Linggau', '16');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1674', 'Kota Prabumulih', '16');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1701', 'Bengkulu Selatan', '17');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1702', 'Rejang Lebong', '17');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1703', 'Bengkulu Utara', '17');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1704', 'Kaur', '17');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1705', 'Seluma', '17');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1706', 'Muko Muko', '17');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1707', 'Lebong', '17');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1708', 'Kepahiang', '17');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1709', 'Bengkulu Tengah', '17');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1771', 'Kota Bengkulu', '17');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1801', 'Lampung Selatan', '18');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1802', 'Lampung Tengah', '18');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1803', 'Lampung Utara', '18');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1804', 'Lampung Barat', '18');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1805', 'Tulang Bawang', '18');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1806', 'Tanggamus', '18');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1807', 'Lampung Timur', '18');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1808', 'Way Kanan', '18');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1809', 'Pesawaran', '18');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1810', 'Pringsewu', '18');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1811', 'Mesuji', '18');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1812', 'Tulang Bawang Barat', '18');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1813', 'Pesisir Barat', '18');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1871', 'Kota Bandar Lampung', '18');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1872', 'Kota Metro', '18');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1901', 'Bangka', '19');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1902', 'Belitung', '19');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1903', 'Bangka Selatan', '19');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1904', 'Bangka Tengah', '19');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1905', 'Bangka Barat', '19');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1906', 'Belitung Timur', '19');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('1971', 'Kota Pangkal Pinang', '19');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('2101', 'Bintan', '21');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('2102', 'Karimun', '21');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('2103', 'Natuna', '21');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('2104', 'Lingga', '21');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('2105', 'Kepulauan Anambas', '21');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('2171', 'Kota Batam', '21');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('2172', 'Kota Tanjung Pinang', '21');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3101', 'Kepulauan Seribu', '31');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3171', 'Kota Jakarta Pusat', '31');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3172', 'Kota Jakarta Utara', '31');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3173', 'Kota Jakarta Barat', '31');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3174', 'Kota Jakarta Selatan', '31');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3175', 'Kota Jakarta Timur', '31');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3201', 'Bogor', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3202', 'Sukabumi', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3203', 'Cianjur', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3204', 'Bandung', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3205', 'Garut', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3206', 'Tasikmalaya', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3207', 'Ciamis', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3208', 'Kuningan', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3209', 'Cirebon', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3210', 'Majalengka', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3211', 'Sumedang', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3212', 'Indramayu', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3213', 'Subang', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3214', 'Purwakarta', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3215', 'Karawang', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3216', 'Bekasi', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3217', 'Bandung Barat', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3218', 'Pangandaran', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3271', 'Kota Bogor', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3272', 'Kota Sukabumi', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3273', 'Kota Bandung', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3274', 'Kota Cirebon', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3275', 'Kota Bekasi', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3276', 'Kota Depok', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3277', 'Kota Cimahi', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3278', 'Kota Tasikmalaya', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3279', 'Kota Banjar', '32');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3301', 'Cilacap', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3302', 'Banyumas', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3303', 'Purbalingga', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3304', 'Banjarnegara', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3305', 'Kebumen', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3306', 'Purworejo', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3307', 'Wonosobo', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3308', 'Magelang', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3309', 'Boyolali', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3310', 'Klaten', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3311', 'Sukoharjo', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3312', 'Wonogiri', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3313', 'Karanganyar', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3314', 'Sragen', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3315', 'Grobogan', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3316', 'Blora', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3317', 'Rembang', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3318', 'Pati', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3319', 'Kudus', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3320', 'Jepara', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3321', 'Demak', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3322', 'Semarang', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3323', 'Temanggung', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3324', 'Kendal', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3325', 'Batang', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3326', 'Pekalongan', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3327', 'Pemalang', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3328', 'Tegal', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3329', 'Brebes', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3371', 'Kota Magelang', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3372', 'Kota Surakarta', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3373', 'Kota Salatiga', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3374', 'Kota Semarang', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3375', 'Kota Pekalongan', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3376', 'Kota Tegal', '33');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3401', 'Kulon Progo', '34');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3402', 'Bantul', '34');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3403', 'Gunungkidul', '34');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3404', 'Sleman', '34');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3471', 'Kota Yogyakarta', '34');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3501', 'Pacitan', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3502', 'Ponorogo', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3503', 'Trenggalek', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3504', 'Tulungagung', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3505', 'Blitar', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3506', 'Kediri', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3507', 'Malang', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3508', 'Lumajang', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3509', 'Jember', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3510', 'Banyuwangi', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3511', 'Bondowoso', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3512', 'Situbondo', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3513', 'Probolinggo', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3514', 'Pasuruan', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3515', 'Sidoarjo', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3516', 'Mojokerto', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3517', 'Jombang', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3518', 'Nganjuk', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3519', 'Madiun', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3520', 'Magetan', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3521', 'Ngawi', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3522', 'Bojonegoro', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3523', 'Tuban', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3524', 'Lamongan', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3525', 'Gresik', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3526', 'Bangkalan', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3527', 'Sampang', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3528', 'Pamekasan', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3529', 'Sumenep', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3571', 'Kota Kediri', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3572', 'Kota Blitar', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3573', 'Kota Malang', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3574', 'Kota Probolinggo', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3575', 'Kota Pasuruan', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3576', 'Kota Mojokerto', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3577', 'Kota Madiun', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3578', 'Kota Surabaya', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3579', 'Kota Batu', '35');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3601', 'Pandeglang', '36');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3602', 'Lebak', '36');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3603', 'Tangerang', '36');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3604', 'Serang', '36');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3671', 'Kota Tangerang', '36');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3672', 'Kota Cilegon', '36');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3673', 'Kota Serang', '36');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('3674', 'Kota Tangerang Selatan', '36');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5101', 'Jembrana', '51');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5102', 'Tabanan', '51');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5103', 'Badung', '51');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5104', 'Gianyar', '51');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5105', 'Klungkung', '51');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5106', 'Bangli', '51');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5107', 'Karangasem', '51');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5108', 'Buleleng', '51');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5171', 'Kota Denpasar', '51');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5201', 'Lombok Barat', '52');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5202', 'Lombok Tengah', '52');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5203', 'Lombok Timur', '52');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5204', 'Sumbawa', '52');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5205', 'Dompu', '52');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5206', 'Bima', '52');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5207', 'Sumbawa Barat', '52');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5208', 'Lombok Utara', '52');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5271', 'Kota Mataram', '52');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5272', 'Kota Bima', '52');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5301', 'Kupang', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5302', 'Timor Tengah Selatan', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5303', 'Timor Tengah Utara', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5304', 'Belu', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5305', 'Alor', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5306', 'Flores Timur', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5307', 'Sikka', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5308', 'Ende', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5309', 'Ngada', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5310', 'Manggarai', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5311', 'Sumba Timur', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5312', 'Sumba Barat', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5313', 'Lembata', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5314', 'Rote Ndao', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5315', 'Manggarai Barat', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5316', 'Nagekeo', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5317', 'Sumba Tengah', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5318', 'Sumba Barat Daya', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5319', 'Manggarai Timur', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5320', 'Sabu Raijua', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5321', 'Malaka', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('5371', 'Kota Kupang', '53');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6101', 'Sambas', '61');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6102', 'Mempawah', '61');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6103', 'Sanggau', '61');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6104', 'Ketapang', '61');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6105', 'Sintang', '61');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6106', 'Kapuas Hulu', '61');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6107', 'Bengkayang', '61');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6108', 'Landak', '61');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6109', 'Sekadau', '61');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6110', 'Melawi', '61');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6111', 'Kayong Utara', '61');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6112', 'Kubu Raya', '61');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6171', 'Kota Pontianak', '61');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6172', 'Kota Singkawang', '61');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6201', 'Kotawaringin Barat', '62');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6202', 'Kotawaringin Timur', '62');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6203', 'Kapuas', '62');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6204', 'Barito Selatan', '62');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6205', 'Barito Utara', '62');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6206', 'Katingan', '62');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6207', 'Seruyan', '62');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6208', 'Sukamara', '62');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6209', 'Lamandau', '62');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6210', 'Gunung Mas', '62');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6211', 'Pulang Pisau', '62');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6212', 'Murung Raya', '62');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6213', 'Barito Timur', '62');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6271', 'Kota Palangkaraya', '62');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6301', 'Tanah Laut', '63');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6302', 'Kotabaru', '63');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6303', 'Banjar', '63');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6304', 'Barito Kuala', '63');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6305', 'Tapin', '63');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6306', 'Hulu Sungai Selatan', '63');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6307', 'Hulu Sungai Tengah', '63');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6308', 'Hulu Sungai Utara', '63');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6309', 'Tabalong', '63');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6310', 'Tanah Bumbu', '63');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6311', 'Balangan', '63');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6371', 'Kota Banjarmasin', '63');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6372', 'Kota Banjarbaru', '63');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6401', 'Paser', '64');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6402', 'Kutai Kartanegara', '64');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6403', 'Berau', '64');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6407', 'Kutai Barat', '64');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6408', 'Kutai Timur', '64');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6409', 'Penajam Paser Utara', '64');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6411', 'Mahakam Ulu', '64');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6471', 'Kota Balikpapan', '64');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6472', 'Kota Samarinda', '64');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6474', 'Kota Bontang', '64');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6501', 'Bulungan', '65');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6502', 'Malinau', '65');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6503', 'Nunukan', '65');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6504', 'Tana Tidung', '65');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('6571', 'Kota Tarakan', '65');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7101', 'Bolaang Mongondow', '71');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7102', 'Minahasa', '71');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7103', 'Kepulauan Sangihe', '71');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7104', 'Kepulauan Talaud', '71');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7105', 'Minahasa Selatan', '71');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7106', 'Minahasa Utara', '71');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7107', 'Minahasa Tenggara', '71');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7108', 'Bolaang Mongondow Utara', '71');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7109', 'Kepulauan Siau Tagulandang Biaro (Sitaro)', '71');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7110', 'Bolaang Mongondow Timur', '71');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7111', 'Bolaang Mongondow Selatan', '71');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7171', 'Kota Manado', '71');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7172', 'Kota Bitung', '71');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7173', 'Kota Tomohon', '71');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7174', 'Kota Kotamobagu', '71');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7201', 'Banggai', '72');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7202', 'Poso', '72');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7203', 'Donggala', '72');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7204', 'Toli Toli', '72');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7205', 'Buol', '72');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7206', 'Morowali', '72');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7207', 'Banggai Kepulauan', '72');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7208', 'Parigi Moutong', '72');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7209', 'Tojo Una Una', '72');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7210', 'Sigi', '72');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7211', 'Banggai Laut', '72');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7212', 'Morowali Utara', '72');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7271', 'Kota Palu', '72');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7301', 'Kepulauan Selayar', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7302', 'Bulukumba', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7303', 'Bantaeng', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7304', 'Jeneponto', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7305', 'Takalar', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7306', 'Gowa', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7307', 'Sinjai', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7308', 'Bone', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7309', 'Maros', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7310', 'Pangkajene Kepulauan', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7311', 'Barru', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7312', 'Soppeng', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7313', 'Wajo', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7314', 'Sidenreng Rappang', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7315', 'Pinrang', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7316', 'Enrekang', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7317', 'Luwu', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7318', 'Tana Toraja', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7322', 'Luwu Utara', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7324', 'Luwu Timur', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7326', 'Toraja Utara', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7371', 'Kota Makassar', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7372', 'Kota Pare Pare', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7373', 'Kota Palopo', '73');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7401', 'Kolaka', '74');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7402', 'Konawe', '74');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7403', 'Muna', '74');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7404', 'Buton', '74');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7405', 'Konawe Selatan', '74');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7406', 'Bombana', '74');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7407', 'Wakatobi', '74');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7408', 'Kolaka Utara', '74');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7409', 'Konawe Utara', '74');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7410', 'Buton Utara', '74');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7411', 'Kolaka Timur', '74');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7412', 'Konawe Kepulauan', '74');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7413', 'Muna Barat', '74');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7414', 'Buton Tengah', '74');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7415', 'Buton Selatan', '74');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7471', 'Kota Kendari', '74');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7472', 'Kota Bau Bau', '74');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7501', 'Gorontalo', '75');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7502', 'Boalemo', '75');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7503', 'Bone Bolango', '75');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7504', 'Pahuwato', '75');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7505', 'Gorontalo Utara', '75');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7571', 'Kota Gorontalo', '75');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7601', 'Pasangkayu (Mamuju Utara)', '76');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7602', 'Mamuju', '76');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7603', 'Mamasa', '76');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7604', 'Polewali Mandar', '76');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7605', 'Majene', '76');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('7606', 'Mamuju Tengah', '76');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8101', 'Maluku Tengah', '81');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8102', 'Maluku Tenggara', '81');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8103', 'Kepulauan Tanimbar (Maluku Tenggara Barat)', '81');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8104', 'Buru', '81');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8105', 'Seram Bagian Timur', '81');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8106', 'Seram Bagian Barat', '81');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8107', 'Kepulauan Aru', '81');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8108', 'Maluku Barat Daya', '81');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8109', 'Buru Selatan', '81');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8171', 'Kota Ambon', '81');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8172', 'Kota Tual', '81');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8201', 'Halmahera Barat', '82');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8202', 'Halmahera Tengah', '82');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8203', 'Halmahera Utara', '82');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8204', 'Halmahera Selatan', '82');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8205', 'Kepulauan Sula', '82');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8206', 'Halmahera Timur', '82');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8207', 'Pulau Morotai', '82');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8208', 'Pulau Taliabu', '82');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8271', 'Kota Ternate', '82');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('8272', 'Kota Tidore Kepulauan', '82');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9103', 'Jayapura', '91');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9105', 'Kepulauan Yapen', '91');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9106', 'Biak Numfor', '91');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9110', 'Sarmi', '91');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9111', 'Keerom', '91');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9115', 'Waropen', '91');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9119', 'Supiori', '91');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9120', 'Mamberamo Raya', '91');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9171', 'Kota Jayapura', '91');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9202', 'Manokwari', '92');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9203', 'Fak Fak', '92');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9206', 'Teluk Bintuni', '92');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9207', 'Teluk Wondama', '92');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9208', 'Kaimana', '92');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9211', 'Manokwari Selatan', '92');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9212', 'Pegunungan Arfak', '92');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9301', 'Merauke', '93');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9302', 'Boven Digoel', '93');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9303', 'Mappi', '93');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9304', 'Asmat', '93');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9401', 'Nabire', '94');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9402', 'Puncak Jaya', '94');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9403', 'Paniai', '94');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9404', 'Mimika', '94');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9405', 'Puncak', '94');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9406', 'Dogiyai', '94');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9407', 'Intan Jaya', '94');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9408', 'Deiyai', '94');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9501', 'Jayawijaya', '95');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9502', 'Pegunungan Bintang', '95');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9503', 'Yahukimo', '95');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9504', 'Tolikara', '95');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9505', 'Mamberamo Tengah', '95');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9506', 'Yalimo', '95');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9507', 'Lanny Jaya', '95');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9508', 'Nduga', '95');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9601', 'Sorong', '96');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9604', 'Sorong Selatan', '96');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9605', 'Raja Ampat', '96');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9609', 'Tambrauw', '96');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9610', 'Maybrat', '96');
INSERT INTO tb_kota_kab (id_kota_kab, nama, provinsi_id) VALUES ('9671', 'Kota Sorong', '96');
