INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('11', 'Aceh');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('12', 'Sumatera Utara');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('13', 'Sumatera Barat');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('14', 'Riau');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('15', 'Jambi');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('16', 'Sumatera Selatan');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('17', 'Bengkulu');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('18', 'Lampung');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('19', 'Kepulauan Bangka Belitung');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('21', 'Kepulauan Riau');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('31', 'DKI Jakarta');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('32', 'Jawa Barat');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('33', 'Jawa Tengah');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('34', 'DI Yogyakarta');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('35', 'Jawa Timur');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('36', 'Banten');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('51', 'Bali');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('52', 'Nusa Tenggara Barat');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('53', 'Nusa Tenggara Timur');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('61', 'Kalimantan Barat');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('62', 'Kalimantan Tengah');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('63', 'Kalimantan Selatan');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('64', 'Kalimantan Timur');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('65', 'Kalimantan Utara');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('71', 'Sulawesi Utara');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('72', 'Sulawesi Tengah');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('73', 'Sulawesi Selatan');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('74', 'Sulawesi Tenggara');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('75', 'Gorontalo');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('76', 'Sulawesi Barat');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('81', 'Maluku');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('82', 'Maluku Utara');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('91', 'Papua');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('92', 'Papua Barat');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('93', 'Papua Selatan');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('94', 'Papua Tengah');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('95', 'Papua Pegunungan');
INSERT INTO tb_provinsi (id_provinsi, nama) VALUES ('96', 'Papua Barat Daya');
